#!/bin/bash

. ./hooks/env

docker build \
  --build-arg VERSION="${PKG_VER}"  \
  --build-arg COMMIT="${SOURCE_COMMIT}" \
  --build-arg BRANCH="${SOURCE_BRANCH}" \
  --build-arg VCS_URL="${VCS_URL}" \
  --build-arg BUILD_DATE="${BUILD_DATE}" \
  --build-arg ALPINE_VER="${ALPINE_VER}" \
  --build-arg PYTHON_VER="${PYTHON_VER}" \
  --build-arg BASEIMAGE_ARCH="${BASEIMAGE_ARCH}" \
  --build-arg PKG_ARCH="${PKG_ARCH}" \
  --build-arg QEMU_ARCH="${QEMU_ARCH}" \
-f "${DOCKERFILE_PATH}" \
-t "${DOCKER_REPO}:latest-${DOCKER_ARCH}" \
-t "${IMAGE_NAME}" . \
| while read line ; do echo "$(date)| $line"; done;
