name: autotag

on:
  push:
    paths:
      - requirements.txt
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "requirements.txt"
        extraction_regex: "appdaemon==(\\d+.\\d+.\\d+)"
        tag_message: ""
